name: Build and Install Dependencies

on:
  push:
    branches:
      - main  # Sostituisci "main" con il nome del tuo branch principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Sostituisci con la versione di Node.js che usi

      - name: Install Dependencies
        run: npm install